from pathlib import Path
from github import Github
from git import Repo
from github import Auth
import os
from openai import OpenAI
import ast
import subprocess
import tempfile
import re
from coverage import Coverage
import shutil
import json

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
MODEL = "gpt-5.4"
TOKEN = os.getenv("PAT")
auth = Auth.Token(TOKEN)
AGENT_DIR = os.path.abspath(os.path.dirname(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(AGENT_DIR, ".."))
max_attempts=5





def llm(prompt: str) -> str:
    response = client.chat.completions.create(
        model=MODEL,
        messages=[{"role": "user", "content": prompt}],
        temperature=0
    )
    return response.choices[0].message.content

def extract_missing_functions(cov_json_path):
    """
    Returns a list of (file_path, function_name) tuples for all functions
    that have missing coverage across the entire project.

    Example return:
        [
            ("src/cart.py", "add_item"),
            ("src/orders.py", "calculate_total")
        ]
    """

    if not os.path.exists(cov_json_path):
        return []

    try:
        with open(cov_json_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception:
        return []

    missing = []

    # Iterate through all files in coverage.json
    for file_path, file_data in data.get("files", {}).items():
        missing_lines = set(file_data.get("missing_lines", []))
        if not missing_lines:
            continue

        # Function-level coverage info
        functions = file_data.get("functions", {})

        for fn_name, fn_info in functions.items():
            start = fn_info.get("lineno")
            end = fn_info.get("end_lineno")

            if start is None or end is None:
                continue

            fn_lines = set(range(start, end + 1))

            # If any missing line overlaps this function → function is missing coverage
            if fn_lines & missing_lines:
                missing.append((file_path, fn_name))

    return missing

def get_test_file_path(source_file):
    base = os.path.splitext(os.path.basename(source_file))[0]
    test_file = f"tests/test_{base}.py"
    return test_file if os.path.exists(test_file) else None



    



def log_iteration(i, category, stdout, stderr, coverage):
    print(f"\n===== ITERATION {i} =====")
    print("Error Category:", category)
    print("Coverage:", coverage)
    print("STDOUT:\n", stdout)
    print("STDERR:\n", stderr)

def copy_project_to_tmp(project_root, tmp_root):
    """
    Copies all .py files from project_root into tmp_root,
    preserving folder structure.
    """
    for root, dirs, files in os.walk(project_root):
        # Compute relative path from project root
        rel_path = os.path.relpath(root, project_root)
        dest_dir = os.path.join(tmp_root, rel_path)
        if not rel_path.startswith(".") and not rel_path.startswith("_"):
                # Create destination directory
                os.makedirs(dest_dir, exist_ok=True)
        
                # Copy only .py files
                for f in files:
                    if f.endswith(".py"):
                        src_file = os.path.join(root, f)
                        dest_file = os.path.join(dest_dir, f)
                        shutil.copy2(src_file, dest_file)

    return tmp_root

def extract_module_error(stderr, stdout, module_name):
    text = stderr + "\n" + stdout
    lines = [line for line in text.splitlines() if module_name in line or "ERROR" in line]
    return "\n".join(lines)

def run_pytest(tmp):
     # Run pytest with coverage on the specific source file
    result = subprocess.run(
        ["pytest", "--maxfail=1", "--disable-warnings", "-q",
            "--cov=src", "--cov-report=term-missing", "--cov-report=json:coverage.json"],
        cwd=tmp,
        capture_output=True,
        text=True
    )
    print("Pytest completed with return code:", result.stdout+" \n"+result.stderr+"\n "+str(result.returncode))
    return result.stdout, result.stderr, result.returncode



def read_coverage(tmp_root):
    """
    Reads coverage.json generated by pytest-cov and returns the total
    percent_covered as a float. Returns 0.0 if the file is missing or invalid.
    """
    cov_path = os.path.join(tmp_root, "coverage.json")

    if not os.path.exists(cov_path):
        return 0.0

    try:
        with open(cov_path) as f:
            data = json.load(f)

        # pytest-cov stores totals under data["totals"]["percent_covered"]
        return float(data.get("totals", {}).get("percent_covered", 0.0))

    except Exception:
        # If JSON is malformed or missing fields
        return 0.0


def missing_functions_for_module(cov_json_path, module_name):
    """
    Returns a list of function names that have missing coverage
    for the given module (e.g., 'cart', 'orders', etc.).

    Example return:
        ["add_item", "remove_item"]
    """
    if not os.path.exists(cov_json_path):
        return []

    try:
        with open(cov_json_path) as f:
            data = json.load(f)
    except Exception:
        return []

    missing_fns = []

    # Iterate through all files in coverage.json
    for file_path, file_data in data.get("files", {}).items():
        # Only consider this module
        if not file_path.endswith(f"{module_name}.py"):
            continue

        missing_lines = set(file_data.get("missing_lines", []))
        if not missing_lines:
            continue

        # Function-level coverage info
        functions = file_data.get("functions", {})

        for fn_name, fn_info in functions.items():
            start = fn_info.get("lineno")
            end = fn_info.get("end_lineno")

            if start is None or end is None:
                continue

            fn_lines = set(range(start, end + 1))

            # If any missing line overlaps this function → function is missing coverage
            if fn_lines & missing_lines:
                missing_fns.append(fn_name)

    return missing_fns

def refinement_loop(tmp_root,project_root, llm, max_iter=5, min_cov=85):
    
    copy_project_to_tmp(project_root, tmp_root)

    for i in range(1, max_iter + 1):
        stdout, stderr, code = run_pytest(tmp_root)
        coverage = read_coverage(tmp_root)
        cov_json = os.path.join(tmp_root, "coverage.json")

        print(f"\n===== ITERATION {i} =====")
        print("Coverage:", coverage)

        if code == 0 and coverage >= min_cov:
            print("Coverage threshold met.")
            return True

        # Extract missing functions per module
        missing = extract_missing_functions(cov_json)

        # For each module in src/
        for module_file in os.listdir(os.path.join(tmp_root, "src")):
            if not module_file.endswith(".py"):
                continue

            module_name = module_file.replace(".py", "")

            # Missing functions for this module
            missing_fns = missing_functions_for_module(cov_json, module_name)

            # Extract module-specific errors
            module_error = extract_module_error(stderr, stdout, module_name)

            # Generate or refine tests for this module
            generate_tests_for_module(
                tmp_root,
                module_name,
                llm,
                module_error,
                missing_fns
            )


    print("Failed to reach coverage threshold.")
    return False


def load_module_source(tmp_root, module_name):
    """
    Loads and returns the full source code of a module inside tmp_root/src/.

    Example:
        load_module_source("/tmp/refine_abc123", "cart")
        → returns contents of /tmp/refine_abc123/src/cart.py
    """
    module_path = os.path.join(tmp_root, "src", f"{module_name}.py")

    if not os.path.exists(module_path):
        return ""  # Safe fallback for missing modules

    with open(module_path, "r", encoding="utf-8") as f:
        return f.read()
    
def generate_tests_for_module(tmp_root, module_name, llm, error_output, missing_fns):
    """
    Generates or refines tests for a single module.
    If a test file exists AND coverage for this module is already 100%,
    the function skips regeneration.
    """

    # Path to module test file
    test_path = os.path.join(tmp_root, "tests", f"test_{module_name}.py")

    # Load module source
    module_source = load_module_source(tmp_root, module_name)

    # Load existing test file (if any)
    test_file = ""
    if os.path.exists(test_path):
        with open(test_path, "r", encoding="utf-8") as f:
            test_file = f.read()

    # Load coverage.json
    cov_json_path = os.path.join(tmp_root, "coverage.json")
    module_missing = missing_functions_for_module(cov_json_path, module_name)

    # If test exists AND no missing functions → coverage is 100% → skip regeneration
    if os.path.exists(test_path) and len(module_missing) == 0:
        print(f"[SKIP] Module '{module_name}' already has full coverage.")
        return

    # Build module-specific prompt
    prompt = MODULE_PROMPT.format(
        module_name=module_name,
        module_source=module_source,
        test_file=test_file,
        error_output=error_output,
        missing_functions=module_missing
    )

    # Generate new tests
    new_tests = llm(prompt)

    # Write updated test file
    with open(test_path, "w", encoding="utf-8") as f:
        f.write(new_tests)

    print(f"[UPDATED] Regenerated tests for module '{module_name}'.")


MODULE_PROMPT = """
You are generating or fixing pytest tests for a single module.

==========================
MODULE NAME
==========================
{module_name}

==========================
MODULE SOURCE CODE
==========================
{module_source}

==========================
CURRENT TEST FILE (if exists)
==========================
{test_file}

==========================
PYTEST ERROR OUTPUT (for this module)
==========================
{error_output}

==========================
MISSING FUNCTIONS (from coverage)
==========================
{missing_functions}

==========================
MANDATORY RULES
==========================

1. Output MUST be valid Python ONLY.
   - No Markdown.
   - No backticks.
   - No code fences.

2. The test file MUST begin with this exact header:

import sys
import os
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

3. All imports MUST use:
   from src.{module_name} import <symbol>

4. NEVER use:
   import {module_name}
   from {module_name} import X
   import src
   import src.{module_name}
   sys.path.append("src")

5. Generate tests for ALL functions and methods in this module.
6. Include normal cases, edge cases, and exception cases.
7. Tests must be deterministic and minimal.
8. Output MUST be a single complete pytest file for this module.

Now regenerate the full corrected test file for this module.
"""

def copy_tests_from_tmp(tmp_root, real_project_root):
    """
    Copies all test_*.py files from tmp_root/tests/ into
    real_project_root/tests/, preserving filenames.
    """
    try:
        tmp_tests = os.path.join(tmp_root, "tests")
        real_tests = os.path.join(real_project_root, "tests")

        for root, dirs, files in os.walk(tmp_tests):
                print("ROOT:", root)
                print("DIRS:", dirs)
                print("FILES:", files)
                print("-" * 40)

        if not os.path.exists(tmp_tests):
            print("[WARN] No tests directory found in tmp project.")
            return

        os.makedirs(real_tests, exist_ok=True)

        test_dir = os.path.join(tmp_root, "tests")
        os.makedirs(test_dir, exist_ok=True)

        g = Github(auth=auth)
        repo = g.get_repo("kramalakshmi/API")
        
        for file in os.listdir(tmp_tests):
            if file.endswith(".py"):
                src = str(os.path.join(tmp_tests, file))
                dst = str(os.path.join(real_tests, file))[1:]
                print(f"Copying {src} to {dst}...")
                with open(src) as f:
                    test_code = f.read()
                
                try:
            
                    existing = repo.get_contents(dst,ref="mutli_refinement")
                    
                    repo.update_file(
                        dst, "Update generated tests", test_code, existing.sha, branch= "mutli_refinement"
                    )
                except Exception as ex:
                    repo.create_file(
                        dst, "Add generated tests", test_code , branch= "mutli_refinement"
                    )
                
                
                print(f"[COPIED] {file} → {real_tests}")
    except Exception as e:
        print(f"[ERROR] Failed to copy tests: {e}")

if __name__ == "__main__":
    tmp_root = tempfile.mkdtemp(prefix="refine_")
    refinement_loop(tmp_root, PROJECT_ROOT, llm)
    copy_tests_from_tmp(tmp_root, PROJECT_ROOT)
